/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { CallAnalytics } from './callAnalytics';
import type { CallCallMetadata } from './callCallMetadata';
import type { CallDeletedAt } from './callDeletedAt';
import type { CallPromptId } from './callPromptId';
import type { CallReport } from './callReport';
import type { CallTranscript } from './callTranscript';
import type { CallType } from './callType';

export interface Call {
  agent_id: string;
  analytics?: CallAnalytics;
  branch_id: string;
  call_metadata?: CallCallMetadata;
  call_timestamp?: string;
  caller_name?: string;
  created_at?: string;
  deleted_at?: CallDeletedAt;
  id: string;
  lead_id: string;
  object?: string;
  organization_id: string;
  profile_snapshot_id: string;
  prompt_id?: CallPromptId;
  report?: CallReport;
  transcript?: CallTranscript;
  type?: CallType;
  updated_at?: string;
  user_id: string;
}
