/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type CallType = typeof CallType[keyof typeof CallType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallType = {
  appointment_call: 'appointment_call',
  meeting_call: 'meeting_call',
} as const;
