/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { Call } from './call';
import type { ProfileSnapshot } from './profileSnapshot';

export interface CallResponse {
  call: Call;
  profile_snapshot: ProfileSnapshot;
}
