/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { LeadStatus } from './leadStatus';

export type CreatePromptRequestMeetingStatus = LeadStatus | null;
