/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { CallType } from './callType';

export interface CreateCallRequest {
  call_type: CallType;
  lead_id: string;
  prompt_id: string;
}
