/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { CreatePromptRequestKnownToAgent } from './createPromptRequestKnownToAgent';
import type { CreatePromptRequestMeetingStatus } from './createPromptRequestMeetingStatus';
import type { PromptType } from './promptType';

export interface CreatePromptRequest {
  branch_id: string;
  description: string;
  known_to_agent?: CreatePromptRequestKnownToAgent;
  meeting_status?: CreatePromptRequestMeetingStatus;
  name: string;
  prompt_type?: PromptType;
  report_prompt_text: string;
  text: string;
}
