/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { CreateLeadRequestProfile } from './createLeadRequestProfile';
import type { LeadType } from './leadType';

export interface CreateLeadRequest {
  branch_id: string;
  profile?: CreateLeadRequestProfile;
  type: LeadType;
}
