/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { InviteDeletedAt } from './inviteDeletedAt';
import type { Role } from './role';
import type { InviteStatus } from './inviteStatus';

export interface Invite {
  branch_id: string;
  created_at?: string;
  deleted_at?: InviteDeletedAt;
  email: string;
  id: string;
  invited_by: string;
  name?: string;
  object?: string;
  organization_id: string;
  organization_name?: string;
  role: Role;
  status?: InviteStatus;
  token: string;
  updated_at?: string;
}
