/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type InviteStatus = typeof InviteStatus[keyof typeof InviteStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteStatus = {
  pending: 'pending',
  accepted: 'accepted',
  rejected: 'rejected',
  expired: 'expired',
} as const;
