/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type LeadStatus = typeof LeadStatus[keyof typeof LeadStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadStatus = {
  Yet_to_Contact: 'Yet to Contact',
  'Contacted_&_Dropped': 'Contacted & Dropped',
  '1st_Meeting_Scheduled': '1st Meeting Scheduled',
  '1st_Meeting_Completed': '1st Meeting Completed',
  '2nd_Meeting_Scheduled': '2nd Meeting Scheduled',
  Call_Closed: 'Call Closed',
} as const;
