/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type LeadType = typeof LeadType[keyof typeof LeadType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadType = {
  suspect: 'suspect',
  prospect: 'prospect',
} as const;
