/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { LeadAssociatedAgent } from './leadAssociatedAgent';
import type { LeadDeletedAt } from './leadDeletedAt';
import type { LeadKnownToAgent } from './leadKnownToAgent';
import type { LeadMeetingDate } from './leadMeetingDate';
import type { LeadStatus } from './leadStatus';
import type { LeadType } from './leadType';

export interface Lead {
  associated_agent?: LeadAssociatedAgent;
  branch_id: string;
  created_at?: string;
  created_by_id?: string;
  created_by_name?: string;
  deleted_at?: LeadDeletedAt;
  id: string;
  known_to_agent?: LeadKnownToAgent;
  meeting_date?: LeadMeetingDate;
  object?: string;
  organization_id: string;
  status?: LeadStatus;
  type?: LeadType;
  updated_at?: string;
}
