/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * refreshmint backend
 * OpenAPI spec version: 0.1.0
 */

export type MetricsGetMetricsTrendsParams = {
start_date: string;
end_date: string;
branch_id: string;
};
