/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type MetricsGetMetricsGraphParams = {
start_date: string;
end_date: string;
granularity: string;
branch_id: string;
};
