/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { ProfileAge } from './profileAge';
import type { ProfileBudgetConscious } from './profileBudgetConscious';
import type { ProfileCarLoan } from './profileCarLoan';
import type { ProfileCity } from './profileCity';
import type { ProfileCityTier } from './profileCityTier';
import type { ProfileConcernsAndPriorities } from './profileConcernsAndPriorities';
import type { ProfileContactNumber } from './profileContactNumber';
import type { ProfileCountry } from './profileCountry';
import type { ProfileDecisionMakingStyle } from './profileDecisionMakingStyle';
import type { ProfileDeletedAt } from './profileDeletedAt';
import type { ProfileDependents } from './profileDependents';
import type { ProfileDesignation } from './profileDesignation';
import type { ProfileDesiredInsuranceCoverage } from './profileDesiredInsuranceCoverage';
import type { ProfileDislikes } from './profileDislikes';
import type { ProfileEarningMembers } from './profileEarningMembers';
import type { ProfileEmail } from './profileEmail';
import type { ProfileExistingInsuranceCoverage } from './profileExistingInsuranceCoverage';
import type { ProfileFinancialLiteracy } from './profileFinancialLiteracy';
import type { ProfileFullName } from './profileFullName';
import type { ProfileGender } from './profileGender';
import type { ProfileHealthStatus } from './profileHealthStatus';
import type { ProfileHomeLoan } from './profileHomeLoan';
import type { ProfileIncomeRange } from './profileIncomeRange';
import type { ProfileLikes } from './profileLikes';
import type { ProfileMaritalStatus } from './profileMaritalStatus';
import type { ProfileOccupation } from './profileOccupation';
import type { ProfileOtherLoan } from './profileOtherLoan';
import type { ProfilePhysicalAddress } from './profilePhysicalAddress';
import type { ProfileSavings } from './profileSavings';
import type { ProfileState } from './profileState';
import type { ProfileTrustLevel } from './profileTrustLevel';
import type { ProfileZipcode } from './profileZipcode';

export interface Profile {
  age?: ProfileAge;
  branch_id: string;
  budget_conscious?: ProfileBudgetConscious;
  car_loan?: ProfileCarLoan;
  city?: ProfileCity;
  city_tier?: ProfileCityTier;
  concerns_and_priorities?: ProfileConcernsAndPriorities;
  contact_number?: ProfileContactNumber;
  country?: ProfileCountry;
  created_at?: string;
  decision_making_style?: ProfileDecisionMakingStyle;
  deleted_at?: ProfileDeletedAt;
  dependents?: ProfileDependents;
  designation?: ProfileDesignation;
  desired_insurance_coverage?: ProfileDesiredInsuranceCoverage;
  dislikes?: ProfileDislikes;
  earning_members?: ProfileEarningMembers;
  email?: ProfileEmail;
  existing_insurance_coverage?: ProfileExistingInsuranceCoverage;
  financial_literacy?: ProfileFinancialLiteracy;
  full_name?: ProfileFullName;
  gender?: ProfileGender;
  health_status?: ProfileHealthStatus;
  home_loan?: ProfileHomeLoan;
  id: string;
  income_range?: ProfileIncomeRange;
  lead_id: string;
  likes?: ProfileLikes;
  marital_status?: ProfileMaritalStatus;
  object?: string;
  occupation?: ProfileOccupation;
  organization_id: string;
  other_loan?: ProfileOtherLoan;
  physical_address?: ProfilePhysicalAddress;
  savings?: ProfileSavings;
  state?: ProfileState;
  trust_level?: ProfileTrustLevel;
  updated_at?: string;
  zipcode?: ProfileZipcode;
}
