/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type PromptType = typeof PromptType[keyof typeof PromptType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PromptType = {
  conversation: 'conversation',
} as const;
