/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { RegisterCallResponseAudioEncoding } from './registerCallResponseAudioEncoding';
import type { RegisterCallResponseAudioWebsocketProtocol } from './registerCallResponseAudioWebsocketProtocol';
import type { RegisterCallResponseCallStatus } from './registerCallResponseCallStatus';
import type { RegisterCallResponseEndCallAfterSilenceMs } from './registerCallResponseEndCallAfterSilenceMs';
import type { RegisterCallResponseFromNumber } from './registerCallResponseFromNumber';
import type { RegisterCallResponseMetadata } from './registerCallResponseMetadata';
import type { RegisterCallResponseRetellLlmDynamicVariables } from './registerCallResponseRetellLlmDynamicVariables';
import type { RegisterCallResponseToNumber } from './registerCallResponseToNumber';

export interface RegisterCallResponse {
  agent_id: string;
  audio_encoding: RegisterCallResponseAudioEncoding;
  audio_websocket_protocol: RegisterCallResponseAudioWebsocketProtocol;
  call_id: string;
  call_status: RegisterCallResponseCallStatus;
  end_call_after_silence_ms?: RegisterCallResponseEndCallAfterSilenceMs;
  from_number?: RegisterCallResponseFromNumber;
  metadata?: RegisterCallResponseMetadata;
  retell_llm_dynamic_variables?: RegisterCallResponseRetellLlmDynamicVariables;
  sample_rate: number;
  to_number?: RegisterCallResponseToNumber;
  [key: string]: any;
 }
