/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type RegisterCallResponseAudioWebsocketProtocol = typeof RegisterCallResponseAudioWebsocketProtocol[keyof typeof RegisterCallResponseAudioWebsocketProtocol];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterCallResponseAudioWebsocketProtocol = {
  web: 'web',
  twilio: 'twilio',
} as const;
