/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type RegisterCallResponseAudioEncoding = typeof RegisterCallResponseAudioEncoding[keyof typeof RegisterCallResponseAudioEncoding];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterCallResponseAudioEncoding = {
  s16le: 's16le',
  mulaw: 'mulaw',
} as const;
