/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */

export type RegisterCallResponseCallStatus = typeof RegisterCallResponseCallStatus[keyof typeof RegisterCallResponseCallStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterCallResponseCallStatus = {
  registered: 'registered',
  ongoing: 'ongoing',
  ended: 'ended',
  error: 'error',
} as const;
