/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { UpdatePromptRequestDescription } from './updatePromptRequestDescription';
import type { UpdatePromptRequestKnownToAgent } from './updatePromptRequestKnownToAgent';
import type { UpdatePromptRequestMeetingStatus } from './updatePromptRequestMeetingStatus';
import type { UpdatePromptRequestName } from './updatePromptRequestName';
import type { UpdatePromptRequestReportPromptText } from './updatePromptRequestReportPromptText';
import type { UpdatePromptRequestText } from './updatePromptRequestText';

export interface UpdatePromptRequest {
  description?: UpdatePromptRequestDescription;
  known_to_agent?: UpdatePromptRequestKnownToAgent;
  meeting_status?: UpdatePromptRequestMeetingStatus;
  name?: UpdatePromptRequestName;
  report_prompt_text?: UpdatePromptRequestReportPromptText;
  text?: UpdatePromptRequestText;
}
