/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateLeadRequestLead } from './updateLeadRequestLead';
import type { UpdateLeadRequestProfile } from './updateLeadRequestProfile';

export interface UpdateLeadRequest {
  lead?: UpdateLeadRequestLead;
  profile?: UpdateLeadRequestProfile;
}
