/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { UserCurrentBranchId } from './userCurrentBranchId';
import type { UserDeletedAt } from './userDeletedAt';
import type { UserDesignation } from './userDesignation';
import type { Role } from './role';

export interface User {
  created_at?: string;
  current_branch_id?: UserCurrentBranchId;
  deleted_at?: UserDeletedAt;
  designation?: UserDesignation;
  email: string;
  full_name: string;
  hashed_password: string;
  id: string;
  is_active?: boolean;
  object?: string;
  organization_id: string;
  role: Role;
  updated_at?: string;
}
