/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { UserRegisterRequestInviteToken } from './userRegisterRequestInviteToken';
import type { UserRegisterRequestOrganizationName } from './userRegisterRequestOrganizationName';

export interface UserRegisterRequest {
  email: string;
  full_name: string;
  invite_token?: UserRegisterRequestInviteToken;
  organization_name?: UserRegisterRequestOrganizationName;
  /** @minLength 8 */
  password: string;
}
