/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * insureai
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponseCurrentBranchId } from './userResponseCurrentBranchId';
import type { UserResponseDeletedAt } from './userResponseDeletedAt';
import type { UserResponseDesignation } from './userResponseDesignation';
import type { Role } from './role';

export interface UserResponse {
  created_at: string;
  current_branch_id: UserResponseCurrentBranchId;
  deleted_at: UserResponseDeletedAt;
  designation: UserResponseDesignation;
  email: string;
  full_name: string;
  id: string;
  is_active: boolean;
  object: string;
  organization_id: string;
  role: Role;
  updated_at: string;
}
